//=============================================================================================================================================
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 1.28-v8-240-240

#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"

static const char *TAG = "ui";
#pragma region VARIABLES
///////////////////// VARIABLES ////////////////////

typedef enum
{
    KNOB_LEFT = 0,  /*!< EVENT: Rotate to the left */
    KNOB_RIGHT,     /*!< EVENT: Rotate to the right */
    KNOB_H_LIM,     /*!< EVENT: Count reaches maximum limit */
    KNOB_L_LIM,     /*!< EVENT: Count reaches the minimum limit */
    KNOB_ZERO,      /*!< EVENT: Count back to 0 */
    KNOB_EVENT_MAX, /*!< EVENT: Number of events */
    KNOB_NONE,      /*!< EVENT: No event */
} knob_event_t;

typedef enum
{
    BUTTON_PRESS_DOWN = 0,
    BUTTON_PRESS_UP,
    BUTTON_PRESS_REPEAT,
    BUTTON_PRESS_REPEAT_DONE,
    BUTTON_SINGLE_CLICK,
    BUTTON_DOUBLE_CLICK,
    BUTTON_MULTIPLE_CLICK,
    BUTTON_LONG_PRESS_START,
    BUTTON_LONG_PRESS_HOLD,
    BUTTON_LONG_PRESS_UP,
    BUTTON_PRESS_END,
    BUTTON_EVENT_MAX,
    BUTTON_NONE_PRESS,
} button_event_t;

// SCREEN: ui_setting_h2
void ui_setting_h2_screen_init(void);
lv_obj_t * ui_setting_h2;
lv_obj_t * label_set_h2;


// SCREEN: ui_setting_timer
void ui_setting_timer_screen_init(void);
lv_obj_t * ui_setting_timer;
lv_obj_t * label_set_timer;
lv_obj_t * label_hour;
lv_obj_t * label_minute;
lv_obj_t * label_colons;
lv_obj_t * label_notice;

// SCREEN: ui_display_error
void ui_display_error_screen_init(void);
lv_obj_t * ui_display_error;
lv_obj_t * label_warning;
lv_obj_t * arc;
lv_obj_t * label_error_message;
lv_obj_t * label_info;
lv_obj_t * qr_code;

// SCREEN: ui_process_setting
void ui_process_setting_screen_init(void);
lv_obj_t * ui_process_setting;
lv_obj_t * label_calib;
lv_obj_t * label_air_flowrate;
lv_obj_t * label_version;
lv_obj_t * label_version_board;
lv_obj_t * label_version_knob;

// SCREEN: ui_setting
void ui_setting_screen_init(void);
lv_obj_t * ui_setting;
lv_obj_t * label_setting;
lv_obj_t * label_option_calib;
lv_obj_t * label_option_version;

// SCREEN: ui_main
void ui_main_screen_init(void);
// void arc_event_cb(lv_event_t *e);
lv_obj_t *ui_main;
// 
lv_obj_t *label_time;
lv_obj_t *label_percent;
lv_obj_t *state_icon;
lv_obj_t *bg_img;


// test arc
lv_style_t style_arc1;
lv_style_t style_arc2;
lv_obj_t *arc1;
lv_obj_t *arc2;
lv_anim_t anim_1;
lv_anim_t anim_2;
//


// EVENTS
lv_obj_t *ui____initial_actions0;

// CUSTOM VARIABLES
knob_state_t knob_state = STOP;
knob_selection_state_t knob_selection_state = STATE_IDLE;
knob_selection_time_t knob_selection_time = TIME_IDLE;
knob_setting_t knob_setting = OPTION_IDLE;
countdown_state_t countdown_state = COUNTDOWN_STOP;

char percentH2_str[4];                      // 
char airFlowRate_str[10] = "10L/min";
uint8_t have_set_timer = true;
uint8_t have_set_h2_percent = true;
char versionBoard[20];
char versionKnob[20];

#pragma endregion VARIABLES
// IMAGES AND IMAGE SETS
#pragma region TEST LVGL SETTINGS
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif
#pragma endregion TEST LVGL SETTINGS
//********************************* */
#pragma region KNOB_EVENT
//********************************* */
void LVGL_knob_event(void *event)
{
    int knob_event = (int)event; // Ép kiểu event về số nguyên
    ESP_LOGI(TAG, "HF---Read knob event: %d", knob_event);
    ESP_LOGI(TAG, "knob_state: %d", knob_state);
#pragma region KNOB_LEFT
    if (knob_event == KNOB_LEFT)
    {
        ESP_LOGI(TAG, "KNOB_LEFT detected");
        // Dash board selection
        
        if (knob_state == SELECTION_STATE)
        {   
            if (knob_selection_state == PAUSE)
            {
                knob_state = SELECTION_TIME;
                //state_icon
                lv_label_set_text(state_icon, ICON_STOP);
                set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                set_color(state_icon, COLOR_WHITE);
                //label_time
                set_font(label_time, FONT_SIZE_TIME_SELECTED);
                set_color(label_time, COLOR_BLUE);
                //label_percent
                set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
                set_color(label_percent, COLOR_WHITE);
            }
            else if (knob_selection_state == RESUME)
            {
                knob_state = RUNNING;
                //state_icon
                lv_label_set_text(state_icon, ICON_RESUME);
                set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                set_color(state_icon, COLOR_WHITE);

                //label_time
                set_font(label_time, FONT_SIZE_TIME_NORMAL);
                set_color(label_time, COLOR_WHITE);
                //label_percent
                set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
                set_color(label_percent, COLOR_WHITE);
                return;
            }   
        }
        else if (knob_state == SELECTION_TIME)
        {
            knob_state = SELECTION_H2;
            //state_icon
            lv_label_set_text(state_icon, ICON_STOP);
            set_font(state_icon, FONT_SIZE_STATE_NORMAL);
            set_color(state_icon, COLOR_WHITE);

            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_SELECTED);
            set_color(label_percent, COLOR_BLUE);
        }
        else if (knob_state == SELECTION_H2)
        {
            knob_state = SELECTION_STATE;
            //state_icon
            lv_label_set_text(state_icon, ICON_STOP);
            set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            set_color(state_icon, COLOR_BLUE);
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_Running); // Font State higher

            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }

        // Status selection
        if (knob_state == RUNNING)
        {
            knob_state = SELECTION_STATE;
            knob_selection_state = RESUME;
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_SelectState);
            //state_icon
            lv_label_set_text(state_icon, ICON_RESUME);
            set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            set_color(state_icon, COLOR_BLUE);
            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }
        else if (knob_state == STOP)
        {
            knob_state = SELECTION_STATE;
            knob_selection_state = PAUSE;
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_Resume);
            //state_icon
            lv_label_set_text(state_icon, ICON_STOP);
            set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            set_color(state_icon, COLOR_BLUE);

            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }

        // Increased timer adjustment
        
        if (knob_state == TIME_SELECTED)
        {
            increase_timer();
            update_setting_timer_labels();
        }

        // Increased H2 adjustment
        if (knob_state == H2_SELECTED)
        {
            percentH2FromKnob += 0.1;
            if (percentH2FromKnob > 4.0)
            {
                percentH2FromKnob = 4.0;
            }
            
            exchange_H2Percent();
            lv_label_set_text(label_percent, percentH2_str);
        }

        if (knob_state == CALIB_AIR_FLOWRATE)
        {
            airFlowRate+= 0.5;
            if (airFlowRate > AIR_FLOWRATE_MAX)
            {
                airFlowRate = AIR_FLOWRATE_MAX;
            }

            exchange_AirFlowRate();
            lv_label_set_text(label_air_flowrate, airFlowRate_str);
            
        }

        if (knob_state == SETTING)
        {
            knob_setting++;
            if (knob_setting > SETTING_MAX_OPTION)
            {
                knob_setting = SETTING_MAX_OPTION;
            }
            
            switch (knob_setting) {
                case OPTION_1:
                    set_color(label_option_calib, COLOR_BLUE);
                    set_font(label_option_calib, FONT_SIZE_OPTION_SELECTED);

                    set_color(label_option_version, COLOR_WHITE);
                    set_font(label_option_version, FONT_SIZE_OPTION_NORMAL);
                    break;
                case OPTION_2:
                    set_color(label_option_version, COLOR_BLUE);
                    set_font(label_option_version, FONT_SIZE_OPTION_SELECTED);

                    set_color(label_option_calib, COLOR_WHITE);
                    set_font(label_option_calib, FONT_SIZE_OPTION_NORMAL);
                    break;
                default:
                    break;
            }
        }
        
        
    }
#pragma endregion KNOB_LEFT
//=====================================================================================
#pragma region KNOB_RIGHT
    if (knob_event == KNOB_RIGHT)
    {
        ESP_LOGI(TAG, "KNOB_RIGHT detected");
        
        // State selection
        if (knob_state == SELECTION_STATE)
        {
            if (knob_selection_state == PAUSE)
            {
                knob_state = SELECTION_H2;
                //state_icon
                lv_label_set_text(state_icon, ICON_STOP);
                set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                set_color(state_icon, COLOR_WHITE);

                //label_time
                set_font(label_time, FONT_SIZE_TIME_NORMAL);
                set_color(label_time, COLOR_WHITE);
                //label_percent
                set_font(label_percent, FONT_SIZE_PERCENT_SELECTED);
                set_color(label_percent, COLOR_BLUE);
            }
            else if (knob_selection_state == RESUME) {
                knob_state = RUNNING;

                //state_icon
                lv_label_set_text(state_icon, ICON_RESUME);
                set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                set_color(state_icon, COLOR_WHITE);

                //label_time
                set_font(label_time, FONT_SIZE_TIME_NORMAL);
                set_color(label_time, COLOR_WHITE);

                //label_percent
                set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
                set_color(label_percent, COLOR_WHITE);
            }
            
            
        }
        else if (knob_state == SELECTION_TIME)
        {
            knob_state = SELECTION_STATE;
            //state_icon
            lv_label_set_text(state_icon, ICON_STOP);
            set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            set_color(state_icon, COLOR_BLUE);
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_SelectState); // Font State higher
            
            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }
        else if (knob_state == SELECTION_H2)
        {
            knob_state = SELECTION_TIME;
            //state_icon
            lv_label_set_text(state_icon, ICON_STOP);
            set_font(state_icon, FONT_SIZE_STATE_NORMAL);
            set_color(state_icon, COLOR_WHITE);
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_Running); // Font time higher
            
            //label_time
            set_font(label_time, FONT_SIZE_TIME_SELECTED);
            set_color(label_time, COLOR_BLUE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }

        // Status selection
        if (knob_state == RUNNING)
        {
            knob_state = SELECTION_STATE;
            knob_selection_state = RESUME;
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_SelectState);
            //state_icon
            lv_label_set_text(state_icon, ICON_RESUME);
            set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            set_color(state_icon, COLOR_BLUE);
            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }
        else if (knob_state == STOP)
        {
            knob_state = SELECTION_STATE;
            knob_selection_state = PAUSE;
            // _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &Dash_Resume);
            //state_icon
            lv_label_set_text(state_icon, ICON_STOP);
            set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            set_color(state_icon, COLOR_BLUE);

            //label_time
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            set_color(label_time, COLOR_WHITE);
            //label_percent
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            set_color(label_percent, COLOR_WHITE);
        }

        // Decreased timer adjustment
        if (knob_state == TIME_SELECTED)
        {
            decrease_timer();
            update_setting_timer_labels();
        }
        

        // Decreased H2 adjustment
        if (knob_state == H2_SELECTED)
        {
            percentH2FromKnob-=0.1;
            if (percentH2FromKnob < 0.0)
            {
                percentH2FromKnob = 0.0;
            }
            
            exchange_H2Percent();
            lv_label_set_text(label_percent, percentH2_str);
        }

        if (knob_state == CALIB_AIR_FLOWRATE)
        {
            airFlowRate-=0.5;
            if (airFlowRate < AIR_FLOWRATE_MIN)
            {
                airFlowRate = AIR_FLOWRATE_MIN;
            }

            exchange_AirFlowRate();
            lv_label_set_text(label_air_flowrate, airFlowRate_str);
            
        }
        

        if (knob_state == SETTING)
        {
            knob_setting--;
            if (knob_setting < OPTION_IDLE)
            {
                knob_setting = OPTION_1;
            }

            switch (knob_setting) {
                case OPTION_1:
                    set_color(label_option_calib, COLOR_BLUE);
                    set_font(label_option_calib, FONT_SIZE_OPTION_SELECTED);

                    set_color(label_option_version, COLOR_WHITE);
                    set_font(label_option_version, FONT_SIZE_EQUATION_OPTION);
                    break;
                case OPTION_2:
                    set_color(label_option_version, COLOR_BLUE);
                    set_font(label_option_version, FONT_SIZE_OPTION_SELECTED);

                    set_color(label_option_calib, COLOR_WHITE);
                    set_font(label_option_calib, FONT_SIZE_EQUATION_OPTION);
                    break;
                default:
                    break;
            }
        }
        
        
    }
#pragma endregion KNOB_RIGHT 
}
#pragma endregion KNOB_EVENT
//=====================================================================================
#pragma region BUTTON_EVENT
//********************************* */
void LVGL_button_event(void *event)
{
    static uint8_t last_event = BUTTON_PRESS_DOWN;
    int btn_event = (int)event;

    ESP_LOGD(TAG, "HF---Read event: %d", btn_event);

    if (btn_event == BUTTON_SINGLE_CLICK)
    {
        ESP_LOGD(TAG, "BUTTON_SINGLE_CLICK");

        if (last_event == BUTTON_LONG_PRESS_START)
        {
            last_event = BUTTON_SINGLE_CLICK;
            return;
        }

        // Status selection
        if (knob_state == SELECTION_STATE) 
        {
            if (knob_selection_state == RESUME) 
            {
                // Gửi H2 = 0% tới board
                percentH2FromKnob = 0.0;
                savedDataToSend = true;

                // Cập nhật trạng thái
                knob_state = STOP;
                lv_label_set_text(state_icon, ICON_STOP);
                set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                set_color(state_icon, COLOR_WHITE);

                // Kiểm tra nếu chưa đặt thời gian thì đặt lại trạng thái
                have_set_timer = (strcmp(timerFromKnob, "00:00:00") != 0);
                have_set_h2_percent = (strcmp(percentH2_str, "0.0%") != 0);

                pause_countdown();
                delete_animation(arc1);
                delete_animation(arc2);
            }
            else if (knob_selection_state == PAUSE) 
            {
                parsePercentage(); // Chuyển đổi phần trăm H2
                have_set_timer = (strcmp(timerFromKnob, "00:00:00") != 0);
                have_set_h2_percent = (strcmp(percentH2_str, "0.0%") != 0);
                if (!have_set_timer && strcmp(timerFromKnob, "00:00:00") == 0) 
                {
                    // Yêu cầu người dùng đặt thời gian
                    knob_state = SELECTION_TIME;
                    lv_label_set_text(state_icon, ICON_STOP);
                    set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                    set_color(state_icon, COLOR_WHITE);

                    set_color(label_time, COLOR_BLUE);
                    set_font(label_time, FONT_SIZE_TIME_SELECTED);
                    lv_label_set_text(label_notice, "Please set timer");
                    return;
                }
                else if (!have_set_h2_percent && (strcmp(percentH2_str, "0.0%") == 0)) 
                {
                    // Yêu cầu người dùng đặt % H2
                    knob_state = SELECTION_H2;
                    lv_label_set_text(state_icon, ICON_STOP);
                    set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                    set_color(state_icon, COLOR_WHITE);

                    set_color(label_percent, COLOR_BLUE);
                    set_font(label_percent, FONT_SIZE_PERCENT_SELECTED);
                    lv_label_set_text(label_notice, "Please set H2 percent");
                    return;
                }
                else 
                {
                    // Nếu mọi điều kiện đã thỏa mãn, tiếp tục chạy
                    savedDataToSend = true;
                    knob_state = RUNNING;

                    lv_label_set_text(state_icon, ICON_RESUME);
                    set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                    set_color(state_icon, COLOR_WHITE);

                    // Cập nhật giao diện
                    set_font(label_time, FONT_SIZE_TIME_NORMAL);
                    set_color(label_time, COLOR_WHITE);
                    set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
                    set_color(label_percent, COLOR_WHITE);

                    if ((have_set_timer) && countdown_state == COUNTDOWN_STOP) // Chỉ xử lý nếu đã đặt thời gian
                    {
                        save_data_to_nvs(timerFromKnob, &percentH2FromKnob);
                        start_countdown();
                        start_animation(anim_1, arc1);
                        start_animation(anim_2, arc2);
                        return;
                    }
                    resume_countdown();
                    start_animation(anim_1, arc1);
                    start_animation(anim_2, arc2);
                }
            }
        } 
        
        if (knob_state == SELECTION_TIME)
        {
            knob_state = TIME_SELECTED;
            // Màu của chữ sẽ chuyển màu xanh
            //switch ui
            switch_ui(ui_setting_timer, label_notice);
            lv_label_set_text(label_notice, "");
            set_color(label_hour, COLOR_BLUE);
            set_color(label_minute, COLOR_BLUE);
            update_setting_timer_labels();
        } 
        else if (knob_state == TIME_SELECTED)
        {
            // knob_state = STOP;
            set_color(label_time, COLOR_WHITE);
            set_font(label_time, FONT_SIZE_TIME_NORMAL);
            lv_obj_align(label_time, LV_ALIGN_CENTER, 0, 0);

            timerFromKnob[6] = '0';
            timerFromKnob[7] = '0';
            lv_label_set_text(label_time, timerFromKnob);
            //switch ui
            switch_ui(ui_main, label_notice);
            if (timerFromKnob != "00:00:00")
            {
                have_set_timer = true;
                countdown_state = COUNTDOWN_STOP;
            }
            else {
                have_set_timer = false;
            }

            if (have_set_h2_percent == false)
            {
                knob_state = SELECTION_H2;
                set_color(label_percent, COLOR_BLUE);
                set_font(label_percent, FONT_SIZE_PERCENT_SELECTED);
            }
            else if (have_set_h2_percent == true) {
                knob_state = SELECTION_STATE;
                set_color(state_icon, COLOR_BLUE);
                lv_label_set_text(state_icon, ICON_STOP);
                set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            }
            
            // Chuyển trang màn hình hoặc cho chữ từ màu xanh xuống màu trắng nhỏ
            // Kiểm tra xem knob_selection_time là bao nhiêu gửi xuống board.
            // savedDataToSend = true;
            return;
        }

        if (knob_state == SELECTION_H2)
        {
            knob_state = H2_SELECTED;
            set_color(label_percent, COLOR_BLUE);
            parsePercentage();
            lv_label_set_text(label_notice, "");
            // Màu của chữ sẽ chuyển màu xanh
            // switch ui
            switch_ui(ui_setting_h2, label_percent);
            lv_obj_align(label_percent, LV_ALIGN_CENTER, 0, 20);
        }
        else if (knob_state == H2_SELECTED)
        {
            // knob_state = STOP;
            set_color(label_percent, COLOR_WHITE);
            // set_color(ui_percentage, COLOR_WHITE);
            set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
            //switch ui
            switch_ui(ui_main, label_percent);
            lv_obj_align(label_percent, LV_ALIGN_CENTER, 0, 45);
            if (percentH2FromKnob != 0)
            {
                have_set_h2_percent = true;
            }
            else {
                have_set_h2_percent = false;
            }

            if (have_set_timer == false)
            {
                knob_state = SELECTION_TIME;
                set_color(label_time, COLOR_BLUE);
                set_font(label_time, FONT_SIZE_TIME_SELECTED);
            }
            else if (have_set_timer == true) {
                knob_state = SELECTION_STATE;
                set_color(state_icon, COLOR_BLUE);
                lv_label_set_text(state_icon, ICON_STOP);
                set_font(state_icon, FONT_SIZE_STATE_SELECTED);
            }
            
            // Chuyển trang màn hình hoặc cho chữ từ màu xanh xuống màu trắng nhỏ
            // Kiểm tra xem knob_selection_time là bao nhiêu gửi xuống board.
            // savedDataToSend = true;
            return;
        }

        if (knob_state == ERROR)
        {
            knob_state = SHOW_QR;
            lv_obj_add_flag(label_warning, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(label_error_message, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(label_info, LV_OBJ_FLAG_HIDDEN);
            qr_code = lv_img_create(lv_scr_act());
            lv_img_set_src(qr_code, &QR_code);
            lv_obj_align(qr_code, LV_ALIGN_CENTER, 0, 0);
        }
        else if (knob_state == SHOW_QR)
        {
            knob_state = ERROR;
            // lv_obj_del(qr_code);
            lv_obj_clear_flag(label_warning, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(label_error_message, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(label_info, LV_OBJ_FLAG_HIDDEN); 
            lv_obj_add_flag(qr_code, LV_OBJ_FLAG_HIDDEN);
        }
        
        if (knob_state == CALIB_AIR_FLOWRATE)
        {
            if (knob_selection_state == RESUME)
            {
                savedDataToSend = true;
            }

            knob_state = SETTING;
            knob_setting = OPTION_IDLE;

            set_color(label_option_calib, COLOR_WHITE);
            set_font(label_option_calib, FONT_SIZE_OPTION_NORMAL);

            set_color(label_option_version, COLOR_WHITE);
            set_font(label_option_version, FONT_SIZE_OPTION_NORMAL);

            switch_ui(ui_setting, label_setting);
            return;
        }
        else if (knob_state == SHOW_VERSION)
        {
            knob_state = SETTING;
            knob_setting = OPTION_IDLE;

            set_color(label_option_calib, COLOR_WHITE);
            set_font(label_option_calib, FONT_SIZE_OPTION_NORMAL);

            set_color(label_option_version, COLOR_WHITE);
            set_font(label_option_version, FONT_SIZE_OPTION_NORMAL);

            switch_ui(ui_setting, label_setting);
            return;
        }
        

        if (knob_state == SETTING)
        {
            if (knob_setting == OPTION_1)
            {
                knob_state = CALIB_AIR_FLOWRATE;
                switch_ui(ui_process_setting, label_air_flowrate);
                lv_obj_clear_flag(label_calib, LV_OBJ_FLAG_HIDDEN);
                lv_obj_clear_flag(label_air_flowrate, LV_OBJ_FLAG_HIDDEN);
                set_color(label_air_flowrate, COLOR_BLUE);

                lv_obj_add_flag(label_version, LV_OBJ_FLAG_HIDDEN);
                lv_obj_add_flag(label_version_board, LV_OBJ_FLAG_HIDDEN);
                lv_obj_add_flag(label_version_knob, LV_OBJ_FLAG_HIDDEN);
                
            }
            else if (knob_setting == OPTION_2)
            {
                knob_state = SHOW_VERSION;

                lv_obj_add_flag(label_calib, LV_OBJ_FLAG_HIDDEN);
                lv_obj_add_flag(label_air_flowrate, LV_OBJ_FLAG_HIDDEN);

                char labelText[20];
                snprintf(labelText, sizeof(labelText), "BOARD: %s", versionBoard);
                lv_label_set_text(label_version_board, labelText);
                switch_ui(ui_process_setting, label_version);
                lv_obj_clear_flag(label_version, LV_OBJ_FLAG_HIDDEN);
                lv_obj_clear_flag(label_version_board, LV_OBJ_FLAG_HIDDEN);
                lv_obj_clear_flag(label_version_knob, LV_OBJ_FLAG_HIDDEN);
            }
            else if (knob_setting == OPTION_IDLE)
            {
                knob_state = STOP;

                //state_icon
                
                lv_label_set_text(state_icon, ICON_STOP);
                set_font(state_icon, FONT_SIZE_STATE_NORMAL);
                set_color(state_icon, COLOR_WHITE);

                //label_time
                set_font(label_time, FONT_SIZE_TIME_NORMAL);
                set_color(label_time, COLOR_WHITE);
                //label_percent
                set_font(label_percent, FONT_SIZE_PERCENT_NORMAL);
                set_color(label_percent, COLOR_WHITE);

                switch_ui(ui_main, label_notice);
                
            }
            


            
        }
        
        
        

        last_event = BUTTON_SINGLE_CLICK;
    }

    if (btn_event == BUTTON_LONG_PRESS_HOLD)
    {
        ESP_LOGD(TAG, "BUTTON_LONG_PRESS_HOLD");
        if (lv_scr_act() != ui_setting)
        {
            knob_state = SETTING;

            set_color(label_option_calib, COLOR_WHITE);
            set_font(label_option_calib, FONT_SIZE_OPTION_NORMAL);

            set_color(label_option_version, COLOR_WHITE);
            set_font(label_option_version, FONT_SIZE_OPTION_NORMAL);
            switch_ui(ui_setting, label_setting);
        }
        
        last_event = BUTTON_LONG_PRESS_HOLD;
    }
    
}
#pragma endregion BUTTON_EVENT
//********************************* */
#pragma region CUSTOM_FUNCTION
//********************************* */
void exchange_H2Percent() {
    sprintf(percentH2_str, "%.1f%%", percentH2FromKnob);
}

void exchange_AirFlowRate() {
    sprintf(airFlowRate_str, "%.1fL/min", airFlowRate);
}

void set_font(lv_obj_t *obj, const lv_font_t *font) {
    lv_obj_set_style_text_font(obj, font, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void set_color(lv_obj_t *obj, lv_color_t color) {
    lv_obj_set_style_text_color(obj, color, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void reset_ui() {
    knob_state = STOP;
    knob_selection_state = STATE_IDLE;
    knob_selection_time = TIME_IDLE;
    have_set_timer = (strcmp(timerFromKnob, "00:00:00") != 0);
    have_set_h2_percent = (strcmp(percentH2_str, "0.0%") != 0);
    
    if (qr_code != NULL)
    {
        lv_obj_add_flag(qr_code, LV_OBJ_FLAG_HIDDEN);
    }
    delete_animation(arc1);
    delete_animation(arc2);
    // lv_arc_set_value(arc, 0);
    lv_label_set_text(state_icon, ICON_STOP);
    set_font(state_icon, FONT_SIZE_STATE_NORMAL);
    set_color(state_icon, COLOR_WHITE);
    set_font(label_time, FONT_SIZE_TIME_NORMAL);
    set_color(label_time, COLOR_WHITE);
    set_font(label_percent, FONT_SIZE_PERCENT_NORMAL); 
}

void switch_ui(lv_obj_t *screen, lv_obj_t *label) {
    if (label != NULL && (label == label_percent || label == label_notice))
    {
        lv_obj_set_parent(label, screen); //switch label to screen  
    }
    lv_scr_load(screen);    // switch to screen
}

void update_setting_timer_labels() {
    static char hour_str[3];
    static char minute_str[3];
    

    sprintf(hour_str, "%c%c", timerFromKnob[0], timerFromKnob[1]);
    sprintf(minute_str, "%c%c", timerFromKnob[3], timerFromKnob[4]);

    lv_label_set_text(label_hour, hour_str);
    lv_label_set_text(label_minute, minute_str);
}

void increase_timer() {
    int hour = (int)(timerFromKnob[0] - '0') * 10 + (int)(timerFromKnob[1] - '0');
    int minute = (int)(timerFromKnob[3] - '0') * 10 + (int)(timerFromKnob[4] - '0');
    int second = 0;
    minute += 1;
    if (minute == 60)
    {
        minute = 0;
        hour += 1;
        if (hour == 24)
        {
            minute = 0;
            hour = 0;
        }
    } 
    
    // sprintf(timerFromKnob, "%02d:%02d:%s", hour, minute, &timerFromKnob[6]);
    sprintf(timerFromKnob, "%02d:%02d:%02d", hour, minute, second);
}

void decrease_timer() {
    int hour = (int)(timerFromKnob[0] - '0') * 10 + (int)(timerFromKnob[1] - '0');
    int minute = (int)(timerFromKnob[3] - '0') * 10 + (int)(timerFromKnob[4] - '0');
    int second = 0;
    minute -= 1;
    if (minute < 0)
    {
        if (hour >= 1)
        {
            hour -= 1;
            minute = 59;
        }
        else
        {
            minute = 0;
        }  
    }

    sprintf(timerFromKnob, "%02d:%02d:%02d", hour, minute, second);
}

void parsePercentage() {
    char *endptr;
    percentH2FromKnob = strtof(percentH2_str, &endptr);

    if (*endptr == '%') {
        return;
    }
}

void rotate_arc(lv_obj_t *arc, int32_t angle) {
    // lv_arc_set_bg_angles(arc, (120 + angle) % 360, (240 + angle) % 360);
    lv_arc_set_bg_angles(arc, angle % 360, (angle + 350) % 360);
}

void update_arc() {
    int hour = (timerFromKnob[0] - '0') * 10 + (timerFromKnob[1] - '0'); // Lấy giờ
    lv_arc_set_value(arc, hour); // Set giá trị cho Arc
}

void start_animation(lv_anim_t anim, lv_obj_t *arc) {
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_HIDDEN);
    lv_anim_init(&anim);
    lv_anim_set_var(&anim, arc);
    lv_anim_set_exec_cb(&anim, (lv_anim_exec_xcb_t)rotate_arc);
    lv_anim_set_time(&anim, 4500);  // Quay trong 2 giây
    lv_anim_set_values(&anim, 0, 360);
    lv_anim_set_repeat_count(&anim, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&anim);
}

void delete_animation(lv_obj_t *arc) {
    lv_anim_del(arc, (lv_anim_exec_xcb_t)rotate_arc);
    lv_obj_add_flag(arc, LV_OBJ_FLAG_HIDDEN);
}

#pragma endregion CUSTOM_FUNCTION
//************************* */

void arc_event_cb(lv_event_t *e)
{
    // lv_obj_t *arc = lv_event_get_target(e);
    // int32_t value = lv_arc_get_value(arc);

    // Cập nhật màu sắc theo giá trị
    if (error_flag == 1)
    {
        lv_color_t color = lv_color_make(255, 255, 0); // yellow circle
        lv_obj_set_style_arc_color(arc, color, LV_PART_INDICATOR);
    }
    else {
        lv_color_t color = lv_color_make(0, 50 * 2, 255); // blue circle
        // lv_obj_set_style_arc_color(arc, color, LV_PART_INDICATOR);
    }
    
}

#pragma region UI_INIT
///////////////////// UI_INIT ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    

    ui_setting_h2_screen_init();
    ui_setting_timer_screen_init();
    ui_display_error_screen_init();
    ui_process_setting_screen_init();
    ui_setting_screen_init();
    ui_main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
#pragma endregion UI_INIT