// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 1.28-v8-240-240

#include "ui.h"

void ui_display_error_screen_init(void)
{
    // create ui_display_error screen
    ui_display_error = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_display_error, LV_OBJ_FLAG_SCROLLABLE);

    // create background image object
    bg_img = lv_img_create(ui_display_error);
    lv_img_set_src(bg_img, &Idle);
    lv_obj_set_width(bg_img, LV_SIZE_CONTENT);
    lv_obj_set_height(bg_img, LV_SIZE_CONTENT);    
    lv_obj_set_align(bg_img, LV_ALIGN_CENTER);
    lv_obj_clear_flag(bg_img, LV_OBJ_FLAG_SCROLLABLE);      
    lv_obj_align(bg_img, LV_ALIGN_CENTER, 0, 0);
    
    // create arc object
    arc = lv_arc_create(ui_display_error);
    lv_obj_set_size(arc, 235, 235);
    lv_arc_set_range(arc, 0, 24);
    lv_arc_set_value(arc, 24);
    lv_arc_set_bg_start_angle(arc, 0);
    lv_arc_set_bg_end_angle(arc, 360);
    lv_arc_set_rotation(arc, 270);
    lv_obj_remove_style(arc, NULL, LV_PART_KNOB);
    lv_obj_set_style_arc_width(arc, 11, LV_PART_INDICATOR);
    lv_obj_add_event_cb(arc, arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_set_style_arc_opa(arc, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_arc_opa(arc, LV_OPA_COVER, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(arc, true, 0);
    lv_obj_align(arc, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_arc_color(arc, COLOR_YELLOW, LV_PART_INDICATOR);
    lv_obj_center(arc);

    // create label_warning
    label_warning = lv_label_create(ui_display_error);
    lv_obj_set_width(label_warning, LV_SIZE_CONTENT);   
    lv_obj_set_height(label_warning, LV_SIZE_CONTENT);    
    lv_obj_align(label_warning, LV_ALIGN_CENTER, 0, -55);
    lv_label_set_text(label_warning, "WARNING");
    lv_obj_set_style_text_font(label_warning, FONT_SIZE_WARNING, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_error_message
    label_error_message = lv_label_create(ui_display_error);
    lv_obj_set_width(label_error_message, LV_SIZE_CONTENT);   
    lv_obj_set_height(label_error_message, LV_SIZE_CONTENT);    
    lv_obj_align(label_error_message, LV_ALIGN_CENTER, 0, 0);
    lv_label_set_text(label_error_message, "");
    lv_obj_set_style_text_font(label_error_message, FONT_SIZE_ERROR, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_info
    label_info = lv_label_create(ui_display_error);
    lv_obj_set_width(label_info, LV_SIZE_CONTENT);
    lv_obj_set_height(label_info, LV_SIZE_CONTENT);
    lv_obj_align(label_info, LV_ALIGN_CENTER, 0, 55);
    lv_label_set_text(label_info, "Press for more infomation");
    lv_obj_set_style_text_font(label_info, FONT_SIZE_INFO, LV_PART_MAIN | LV_STATE_DEFAULT);

}