// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 1.28-v8-240-240

#include "ui.h"

void ui_main_screen_init(void)
{
    // create screen
    ui_main = lv_obj_create(NULL);                                      
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);                 
    
    // get data from NVS
    get_data_from_nvs(timerFromKnob, &percentH2FromKnob);
    // exchange data to string
    exchange_H2Percent(percentH2FromKnob);                                               

    // create background image object
    bg_img = lv_img_create(ui_main);                                    
    lv_img_set_src(bg_img, &Idle);                                      
    lv_obj_align(bg_img, LV_ALIGN_CENTER, 0, 0);                        
    lv_obj_set_width(bg_img, LV_SIZE_CONTENT);                          
    lv_obj_set_height(bg_img, LV_SIZE_CONTENT);                                        
    lv_obj_clear_flag(bg_img, LV_OBJ_FLAG_SCROLLABLE);   
    // lv_obj_add_flag(bg_img, LV_OBJ_FLAG_HIDDEN);              

    // create arc object
    // arc = lv_arc_create(ui_main);                                       
    // lv_obj_set_size(arc, 235, 235);                                     
    // lv_arc_set_range(arc, 0, 24);                                       
    // lv_arc_set_value(arc, 0);                                           
    // lv_arc_set_bg_start_angle(arc, 0);                                  
    // lv_arc_set_bg_end_angle(arc, 360);                                  
    // lv_arc_set_rotation(arc, 270);                                      
    // lv_obj_remove_style(arc, NULL, LV_PART_KNOB);
    // lv_obj_set_style_arc_width(arc, 11, LV_PART_INDICATOR);
    // lv_obj_add_event_cb(arc, arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    // lv_obj_set_style_arc_opa(arc, LV_OPA_TRANSP, LV_PART_MAIN);
    // lv_obj_set_style_arc_opa(arc, LV_OPA_COVER, LV_PART_INDICATOR);
    // lv_obj_set_style_arc_rounded(arc, true, 0);
    // lv_obj_align(arc, LV_ALIGN_CENTER, 0, 0);
    // lv_obj_center(arc);
    // lv_obj_add_flag(arc, LV_OBJ_FLAG_HIDDEN);

    // Tạo Arc 1 (Màu xanh)
    arc1 = lv_arc_create(ui_main);                                       
    lv_obj_set_size(arc1, 235, 235);                                     
    lv_arc_set_range(arc1, 0, 24);                                       
    lv_arc_set_value(arc1, 10);                                           
    lv_arc_set_bg_start_angle(arc1, 0);                                  
    lv_arc_set_bg_end_angle(arc1, 360);                              
    lv_arc_set_rotation(arc1, 270);                                      
    lv_obj_remove_style(arc1, NULL, LV_PART_KNOB);
    lv_obj_set_style_arc_width(arc1, 11, LV_PART_INDICATOR);
    // lv_obj_add_event_cb(arc1, arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_set_style_arc_opa(arc1, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_arc_opa(arc1, LV_OPA_COVER, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(arc1, true, 0);
    lv_obj_align(arc1, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_arc_color(arc1, COLOR_BLUE, LV_PART_INDICATOR);
    lv_obj_center(arc1);
    lv_obj_add_flag(arc1, LV_OBJ_FLAG_HIDDEN);

    lv_style_init(&style_arc1);
    lv_style_set_arc_color(&style_arc1, lv_color_lighten(COLOR_BLUE, 50));
    lv_style_set_arc_width(&style_arc1, 11);
    lv_obj_add_style(arc1, &style_arc1, LV_PART_INDICATOR);
    
    // lv_anim_init(&anim_1);
    // lv_anim_set_var(&anim_1, arc1);
    // lv_anim_set_exec_cb(&anim_1, (lv_anim_exec_xcb_t)rotate_arc);
    // lv_anim_set_time(&anim_1, 4500);  // Quay trong 2 giây
    // lv_anim_set_values(&anim_1, 0, 360);
    // lv_anim_set_repeat_count(&anim_1, LV_ANIM_REPEAT_INFINITE);
    // lv_anim_start(&anim_1);
    // lv_anim_pause(&anim_1);
    // lv_obj_set_style_shadow_width(arc1, 10, 0);
    // lv_obj_set_style_shadow_color(arc1, COLOR_BLUE, 0);
    // lv_obj_set_style_shadow_spread(arc1, 5, 0);

    // Tạo Arc 2 (Màu hồng)
    arc2 = lv_arc_create(ui_main);                                       
    lv_obj_set_size(arc2, 235, 235);                                     
    lv_arc_set_range(arc2, 0, 24);                                       
    lv_arc_set_value(arc2, 10);                                           
    lv_arc_set_bg_start_angle(arc2, 0);                                  
    lv_arc_set_bg_end_angle(arc2, 360);                                  
    lv_arc_set_rotation(arc2, 90);                                      
    lv_obj_remove_style(arc2, NULL, LV_PART_KNOB);
    lv_obj_set_style_arc_width(arc2, 11, LV_PART_INDICATOR);
    // lv_obj_add_event_cb(arc2, arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_set_style_arc_opa(arc2, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_arc_opa(arc2, LV_OPA_COVER, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(arc2, true, 0);
    lv_obj_align(arc2, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_arc_color(arc2, lv_color_make(255,0,239), LV_PART_INDICATOR);
    lv_obj_center(arc2);
    lv_obj_add_flag(arc2, LV_OBJ_FLAG_HIDDEN);

    // lv_anim_init(&anim_2);
    // lv_anim_set_var(&anim_2, arc2);
    // lv_anim_set_exec_cb(&anim_2, (lv_anim_exec_xcb_t)rotate_arc);
    // lv_anim_set_time(&anim_2, 4500);  // Quay trong 2 giây
    // lv_anim_set_values(&anim_2, 0, 360);
    // lv_anim_set_repeat_count(&anim_2, LV_ANIM_REPEAT_INFINITE);
    // lv_anim_start(&anim_2);
    // lv_anim_pause(&anim_2);
    // lv_obj_set_style_shadow_width(arc2, 10, 0);
    // lv_obj_set_style_shadow_color(arc2, lv_color_make(255,0,239), 0);
    // lv_obj_set_style_shadow_spread(arc2, 5, 0);



    // create state_icon object
    state_icon = lv_label_create(ui_main);
    lv_label_set_text(state_icon, LV_SYMBOL_PLAY);
    lv_obj_set_style_text_font(state_icon, FONT_SIZE_STATE_NORMAL, 0);
    lv_obj_set_style_text_color(state_icon, COLOR_WHITE, 0);
    lv_obj_align(state_icon, LV_ALIGN_CENTER, 0, -50);
    // lv_obj_add_flag(state_icon, LV_OBJ_FLAG_HIDDEN);

    // create label_time
    label_time = lv_label_create(ui_main);
    lv_label_set_text(label_time, timerFromKnob);
    lv_obj_set_style_text_font(label_time, FONT_SIZE_TIME_NORMAL, 0);
    lv_obj_set_style_text_color(label_time, COLOR_WHITE, 0);
    lv_obj_align(label_time, LV_ALIGN_CENTER, 0, 0);
    // lv_obj_add_flag(label_time, LV_OBJ_FLAG_HIDDEN);

    // create label_percent
    label_percent = lv_label_create(ui_main);
    lv_label_set_text(label_percent, percentH2_str);
    lv_obj_set_style_text_font(label_percent, FONT_SIZE_PERCENT_NORMAL, 0);
    lv_obj_set_style_text_color(label_percent, COLOR_WHITE, 0);
    lv_obj_align(label_percent, LV_ALIGN_CENTER, 0, 45);
    // lv_obj_add_flag(label_percent, LV_OBJ_FLAG_HIDDEN);

    // create label_notice
    label_notice = lv_label_create(ui_main);
    lv_label_set_text(label_notice, "");
    lv_obj_set_style_text_font(label_notice, FONT_SIZE_INFO, 0);
    lv_obj_set_style_text_color(label_notice, COLOR_WHITE, 0);
    lv_obj_align(label_notice, LV_ALIGN_CENTER, 0, 70);
    // lv_obj_add_flag(label_notice, LV_OBJ_FLAG_HIDDEN);
}
