// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 1.28-v8-240-240

#include "ui.h"

void ui_process_setting_screen_init(void)
{
    // create ui_process_setting screen
    ui_process_setting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_process_setting, LV_OBJ_FLAG_SCROLLABLE);

    // create label_calib
    label_calib = lv_label_create(ui_process_setting);
    lv_obj_set_width(label_calib, LV_SIZE_CONTENT);
    lv_obj_set_height(label_calib, LV_SIZE_CONTENT);
    lv_obj_align(label_calib, LV_ALIGN_CENTER, 0, -55);
    lv_label_set_text(label_calib, "CALIB");
    lv_obj_set_style_text_font(label_calib, FONT_SIZE_CALIB, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(label_calib, LV_OBJ_FLAG_HIDDEN);

    // create label_air_flowrate
    label_air_flowrate = lv_label_create(ui_process_setting);
    lv_obj_set_width(label_air_flowrate, LV_SIZE_CONTENT);   
    lv_obj_set_height(label_air_flowrate, LV_SIZE_CONTENT);
    lv_obj_align(label_air_flowrate, LV_ALIGN_CENTER, 0, 0);
    lv_label_set_text(label_air_flowrate, airFlowRate_str);
    lv_obj_set_style_text_font(label_air_flowrate, FONT_SIZE_AIR_FLOW_RATE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(label_air_flowrate, LV_OBJ_FLAG_HIDDEN);

    // create label_equation
    label_version = lv_label_create(ui_process_setting);
    lv_obj_set_width(label_version, LV_SIZE_CONTENT);   
    lv_obj_set_height(label_version, LV_SIZE_CONTENT);    
    lv_obj_align(label_version, LV_ALIGN_CENTER, 0, -55);
    lv_label_set_text(label_version, "VERSION");
    lv_obj_set_style_text_font(label_version, FONT_SIZE_EQUATION, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(label_version, LV_OBJ_FLAG_HIDDEN);

    // versionBoard = (char*)malloc(10);  // Cấp phát bộ nhớ cho 50 ký tự
    // strcpy(versionBoard, "v1.0");  // Gán giá trị
    
    // create label_equation_1
    label_version_board = lv_label_create(ui_process_setting);
    lv_obj_set_width(label_version_board, LV_SIZE_CONTENT);   
    lv_obj_set_height(label_version_board, LV_SIZE_CONTENT);    
    lv_obj_align(label_version_board, LV_ALIGN_CENTER, 0, 0);
    // lv_label_set_text(label_version_board, versionBoard);
    lv_obj_set_style_text_font(label_version_board, FONT_SIZE_EQUATION_OPTION, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(label_version_board, LV_OBJ_FLAG_HIDDEN);

    // create label_equation_2
    label_version_knob = lv_label_create(ui_process_setting);
    lv_obj_set_width(label_version_knob, LV_SIZE_CONTENT);   
    lv_obj_set_height(label_version_knob, LV_SIZE_CONTENT);    
    lv_obj_align(label_version_knob, LV_ALIGN_CENTER, 0, 55);
    lv_label_set_text(label_version_knob, "KNOB: v18.3.1");
    lv_obj_set_style_text_font(label_version_knob, FONT_SIZE_EQUATION_OPTION, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(label_version_knob, LV_OBJ_FLAG_HIDDEN);
}
