// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.5.0
// // LVGL version: 8.3.11
// // Project name: 1.28-v8-240-240

// #include "ui.h"
// void ui_setting_timer_screen_init(void)
// {
//     // create ui_setting_timer screen
//     ui_setting_timer = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_setting_timer, LV_OBJ_FLAG_SCROLLABLE);

//     // create label_set_timer
//     label_set_timer = lv_label_create(ui_setting_timer);
//     lv_obj_set_width(label_set_timer, LV_SIZE_CONTENT);
//     lv_obj_set_height(label_set_timer, LV_SIZE_CONTENT);
//     lv_obj_align(label_set_timer, LV_ALIGN_CENTER, 0, -55);
//     lv_label_set_text(label_set_timer, "Set Timer");
//     lv_obj_set_style_text_font(label_set_timer, FONT_SIZE_SETTING_TIMER, LV_PART_MAIN | LV_STATE_DEFAULT);

//     // create label_hour
//     label_hour = lv_label_create(ui_setting_timer);
//     lv_obj_align(label_hour, LV_ALIGN_CENTER, -50, 5);
//     lv_label_set_text(label_hour, "00");
//     lv_obj_set_style_text_font(label_hour, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

//     // create label_minute
//     label_minute = lv_label_create(ui_setting_timer);
//     lv_obj_align(label_minute, LV_ALIGN_CENTER, 40, 5);
//     lv_label_set_text(label_minute, "00");
//     lv_obj_set_style_text_font(label_minute, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

//     // create label_second
//     label_second = lv_label_create(ui_setting_timer);
//     lv_obj_align(label_second, LV_ALIGN_CENTER, 40, 5);
//     lv_label_set_text(label_second, "00");
//     lv_obj_set_style_text_font(label_second, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

//     // create label_colons
//     label_colons = lv_label_create(ui_setting_timer);
//     lv_obj_align(label_colons, LV_ALIGN_CENTER, 0, 5);
//     lv_label_set_text(label_colons, ":");
//     lv_obj_set_style_text_font(label_colons, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_color(label_colons, COLOR_BLUE, 0);

//     // create label_notice
//     label_notice = lv_label_create(ui_setting_timer);
//     lv_obj_align(label_notice, LV_ALIGN_CENTER, 0, 55);
//     lv_label_set_text(label_notice, "");
//     lv_obj_set_style_text_font(label_notice, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

// }
#include "ui.h"

void ui_setting_timer_screen_init(void)
{
    // create ui_setting_timer screen
    ui_setting_timer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setting_timer, LV_OBJ_FLAG_SCROLLABLE);

    // create label_set_timer
    label_set_timer = lv_label_create(ui_setting_timer);
    lv_obj_set_width(label_set_timer, LV_SIZE_CONTENT);
    lv_obj_set_height(label_set_timer, LV_SIZE_CONTENT);
    lv_obj_align(label_set_timer, LV_ALIGN_CENTER, 0, -60); // Dịch lên để nhường chỗ
    lv_label_set_text(label_set_timer, "Set Timer");
    lv_obj_set_style_text_font(label_set_timer, FONT_SIZE_SETTING_TIMER, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_hour
    label_hour = lv_label_create(ui_setting_timer);
    lv_obj_align(label_hour, LV_ALIGN_CENTER, -75, 10); // Dịch trái để cân đối
    lv_label_set_text(label_hour, "00");
    lv_obj_set_style_text_font(label_hour, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT); // Giảm cỡ chữ để vừa màn hình

    // create label_colons (giữa giờ và phút)
    label_colons = lv_label_create(ui_setting_timer);
    lv_obj_align(label_colons, LV_ALIGN_CENTER, -35, 10); // Dịch trái
    lv_label_set_text(label_colons, ":");
    lv_obj_set_style_text_font(label_colons, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label_colons, COLOR_BLUE, 0);

    // create label_minute
    label_minute = lv_label_create(ui_setting_timer);
    lv_obj_align(label_minute, LV_ALIGN_CENTER, 0, 10); // Dịch phải
    lv_label_set_text(label_minute, "00");
    lv_obj_set_style_text_font(label_minute, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_colons2 (giữa phút và giây)
    lv_obj_t *label_colons2 = lv_label_create(ui_setting_timer);
    lv_obj_align(label_colons2, LV_ALIGN_CENTER, 35, 10); // Dịch phải
    lv_label_set_text(label_colons2, ":");
    lv_obj_set_style_text_font(label_colons2, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label_colons2, COLOR_BLUE, 0);

    // create label_second
    label_second = lv_label_create(ui_setting_timer);
    lv_obj_align(label_second, LV_ALIGN_CENTER, 75, 10); // Dịch phải để hiển thị giây
    lv_label_set_text(label_second, "00");
    lv_obj_set_style_text_font(label_second, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label_second, COLOR_BLUE, 0);

    // create label_notice
    label_notice = lv_label_create(ui_setting_timer);
    lv_obj_align(label_notice, LV_ALIGN_CENTER, 0, 60); // Dịch xuống để cân đối
    lv_label_set_text(label_notice, "Set timer in minutes");
    lv_obj_set_style_text_font(label_notice, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
}