// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 1.28-v8-240-240

#include "ui.h"

void ui_setting_h2_screen_init(void)
{
    // create ui_setting_h2 screen
    ui_setting_h2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setting_h2, LV_OBJ_FLAG_SCROLLABLE);

    // create label_set_h2
    label_set_h2 = lv_label_create(ui_setting_h2);
    lv_obj_set_width(label_set_h2, LV_SIZE_CONTENT);
    lv_obj_set_height(label_set_h2, LV_SIZE_CONTENT);
    lv_obj_align(label_set_h2, LV_ALIGN_CENTER, 0, -55);
    lv_label_set_text(label_set_h2, "Set H2%");
    lv_obj_set_style_text_font(label_set_h2, FONT_SIZE_SETTING_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

}