// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 1.28-v8-240-240

#include "ui.h"

void ui_setting_screen_init(void)
{
    // create ui_setting screen
    ui_setting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // create label_setting
    label_setting = lv_label_create(ui_setting);
    lv_obj_set_width(label_setting, LV_SIZE_CONTENT);
    lv_obj_set_height(label_setting, LV_SIZE_CONTENT);
    lv_obj_align(label_setting, LV_ALIGN_CENTER, 0, -55);
    lv_label_set_text(label_setting, "SETTING");
    lv_obj_set_style_text_font(label_setting, FONT_SIZE_SETTING, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_option_calib
    label_option_calib = lv_label_create(ui_setting);
    lv_obj_set_width(label_option_calib, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(label_option_calib, LV_SIZE_CONTENT); /// 1
    lv_obj_align(label_option_calib, LV_ALIGN_CENTER, 0, 0);
    lv_label_set_text(label_option_calib, "1. CALIB");
    lv_obj_set_style_text_font(label_option_calib, FONT_SIZE_OPTION_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_option_version
    label_option_version = lv_label_create(ui_setting);
    lv_obj_set_width(label_option_version, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(label_option_version, LV_SIZE_CONTENT); /// 1
    lv_obj_align(label_option_version, LV_ALIGN_CENTER, 0, 30);
    lv_label_set_text(label_option_version, "2. VERSION");
    lv_obj_set_style_text_font(label_option_version, FONT_SIZE_OPTION_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    // create label_option_ip
    label_option_ip = lv_label_create(ui_setting);
    lv_obj_set_width(label_option_ip, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(label_option_ip, LV_SIZE_CONTENT); /// 1
    lv_obj_align(label_option_ip, LV_ALIGN_CENTER, 0, 60);
    lv_label_set_text(label_option_ip, "3. IP");
    lv_obj_set_style_text_font(label_option_ip, FONT_SIZE_OPTION_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
}
